version: "2"

services:
    python:
      container_name: python
      build: 
        context: .
        dockerfile: .docker/python.dockerfile
      ports:
        - "3000:3000"
      volumes:
        - .:/var/Udacity/ud120
      working_dir: /var/Udacity/ud120
 